public class Test3 {

    public Integer process(Integer extremelyLongParameterNameForCustomerRetryCalculation) {
        Integer retryCalc = 1;
        Integer extremelyLongLocalVariableNameForCustomerRetryCalculation = retryCalc
            + extremelyLongParameterNameForCustomerRetryCalculation;

        for (Integer extremelyLongIndexNameForRetryLoopCalculation = 0;
             extremelyLongIndexNameForRetryLoopCalculation < 2;
             extremelyLongIndexNameForRetryLoopCalculation++) {
            extremelyLongLocalVariableNameForCustomerRetryCalculation += extremelyLongIndexNameForRetryLoopCalculation;
        }

        return extremelyLongLocalVariableNameForCustomerRetryCalculation;
    }
}

